<a href="https://colab.research.google.com/github/Rut092/TRAINING-DATASETS/blob/main/Data_Preprocessing_Lectures_(_1st_Notebook_).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing the Library**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

**Import the Dataset**

In [ ]:
dataset = pd.read_csv('Data.csv')
print(dataset)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
x = dataset.iloc[:,:-1]     #iloc = index location(we can specify which rows to take)(row,column)
y = dataset.iloc[:,-1:]
print(dataset.iloc[:,-1])
print(x,y)

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object
   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0   Purchased
0        No
1       Yes
2        No
3        No
4       Yes
5       Yes
6        No
7       Yes
8        No
9       Yes


In [ ]:
x = dataset.iloc[:,:-1].values   #.values will take all the values
y = dataset.iloc[:,-1].values    # [: , -1] will take all the labels in one array otherwise it will take every value in an seperate array
print(x,y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]] ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


**Taking Care of Missing Data**
* generally we have alot of data if
1% data is missing is good to remove it.
* sometimes we have alot of missing data we have to do it right way
we will do missing value of all the average of all the column

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:])
# make sure to input only numericals values not string fields it does not process string field
imputer.transform(x[:,1:])
x[:,1:] = imputer.transform(x[:,1:])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


1. The Real-World Analogy: The Exam
Think of the imputer like a student preparing for an exam.

>* fit (The Study Phase): The student looks at the textbook (the data) and calculates the average (mean). They now "know" that the average height is 170cm. They haven't changed anything yet; they just have that number stored in their head.

>* transform (The Exam Phase): The student sees a blank spot on the exam paper. Because they "know" the average is 170cm from their study phase, they fill in the blank with "170".

> If you didn't fit first, the student wouldn't know what number to use to fill the gap.

2. The reason is consistency between Training and Testing data.

>* On Training Data: You use fit to calculate the mean. Then you use transform to fill the holes.

>* On New/Test Data: You must not fit again. You want to use the same mean you calculated from the training data to fill holes in the new data.

> If you fit on the test data, you are "cheating" by letting the model see the patterns in the test set before it's supposed to.

**Key Rule: You fit only once (on training data), but you transform everything (training data, test data, and future real-world data).**


In [ ]:
# Encoding Categorical Data
# turn countries(spain,germany,France) into number 0,1,2,....etc
# In this dataset we have 3 countries if we turn them into sequence (0,1,2)
# it will think there is order between these countries and it will think that order matters
# but that is not the case that's why we want to avoid misinterpreted correlation between features and outcome
# we can do ONEHOTENCODING --> turning (3 countries in a Column to 3 Different Columns of binary vectors )


In [ ]:

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# The first column (index 0) is 'Country', which is categorical
# We want to apply OneHotEncoder to this column
# remainder='passthrough' means that all other columns not specified will be kept as they are
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

x = np.array(ct.fit_transform(x))

print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


**Splitting the dataset into Training set and Test set**

In [ ]:
# we should apply feature scaling after the splitting not before !!
# we want all feature to apply into a same scale we do this to overcome
# one feature dominating the other one !

In [ ]:
# if we do before the test dataset will get all the mean and standard
# deviation of the whole dataset we dont want that to happen
# it will cause information leakage

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(Y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(Y_test)

[0 1]


**Feature Scaling !!**

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()
# note : we do not want one hot encoded value which is in the (0,1) into standardasation

X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.transform(X_test[:,3:])

In [ ]:
print(X_train)
print(X_test)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]
[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
